var planets = new Object();

planets = {
  0: {
    'name': 'Earth',
    'conditions': 'Excellent',
    'charAttrs': {
       inMine: false,
       gold: 1,
       diamonds: 0,
       initialGoldPerSec: 1,
       goldPerSec: 1,
       initialDiamondsPerSec: 0.01,
       diamondsPerSec: 0,
       initialMagicFind: 0.50,
       magicFind: 0,
       initialMaxGPS: 1, //increased maximum gold/s*this value
       maxGPS: 1,
       initialMaxDPS: 1,
       maxDPS:1,
       initialClickEfficiency: 5,
       clickEfficiency: 0,
       level: 1,
       xp: 0,
       nextLvlXp: 0,
       initialMaxXpPerSec: 1,
       maxXpPerSec: 1,
       skill: 1,
       minions: new Array(),
       equipment: new Array(),
       // Skills + initial skill values
       goldenAxe: 0,
       blacksmith: 0,
       jeweler: 0,
       trainer: 0,
       allSkills: 0,
       initial_goldenAxe: 0,
       initial_blacksmith: 0,
       initial_jeweler: 0,
       initial_trainer: 0,
       initial_allSkills: 0
    }
  },
  1: {
    'name': 'Jupiter',
    'conditions': 'Acceptable',
    'charAttrs': {
       inMine: false,
       gold: 1,
       diamonds: 0,
       initialGoldPerSec: 0.5,
       goldPerSec: 1,
       initialDiamondsPerSec: 0,
       diamondsPerSec: 0,
       initialMagicFind: -2,
       magicFind: 0,
       initialMaxGPS: 1, //increased maximum gold/s*this value
       maxGPS: 1,
       initialMaxDPS: 1,
       maxDPS:1,
       initialClickEfficiency: 1,
       clickEfficiency: 0,
       level: 1,
       xp: 0,
       nextLvlXp: 0,
       initialMaxXpPerSec: 1,
       maxXpPerSec: 1,
       skill: 1,
       minions: new Array(),
       equipment: new Array(),
       // Skills + initial skill values
       goldenAxe: 0,
       blacksmith: 0,
       jeweler: 0,
       trainer: 0,
       allSkills: 0,
       initial_goldenAxe: -10,
       initial_blacksmith: -15,
       initial_jeweler: -20,
       initial_trainer: 0,
       initial_allSkills: 0
    }
  },
  2: {
    'name': 'Nibiru',
    'conditions': 'Bad',
    'charAttrs': {
       inMine: false,
       gold: 1,
       diamonds: 0,
       initialGoldPerSec: 0.5,
       goldPerSec: 1,
       initialDiamondsPerSec: 0,
       diamondsPerSec: 0,
       initialMagicFind: -3,
       magicFind: 0,
       initialMaxGPS: 1, //increased maximum gold/s*this value
       maxGPS: 1,
       initialMaxDPS: 1,
       maxDPS:1,
       initialClickEfficiency: 1,
       clickEfficiency: 0,
       level: 1,
       xp: 0,
       nextLvlXp: 0,
       initialMaxXpPerSec: 1,
       maxXpPerSec: 1,
       skill: 1,
       minions: new Array(),
       equipment: new Array(),
       // Skills + initial skill values
       goldenAxe: 0,
       blacksmith: 0,
       jeweler: 0,
       trainer: 0,
       allSkills: 0,
       initial_goldenAxe: -30,
       initial_blacksmith: -35,
       initial_jeweler: -50,
       initial_trainer: 0,
       initial_allSkills: 0
    }
  }
};